apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9091
    uid: prometheus
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST

  - name: StorageSage-Daemon
    type: prometheus
    access: proxy
    url: http://storage-sage-daemon:9090
    uid: storage-sage-daemon
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
